version: '3.8'

services:
  media_renamer:
    build: .
    container_name: series-name-changer
    environment:
      - NAME_PREFIX=<file_name>
      - DEFAULT_SEASON=2
      - LANGUAGE=en
    volumes:
      - ./items:/app/items